export const heroBlockDefinition = {
  type: 'hero',
  label: 'Hero Banner',
  icon: 'Sparkles',
  category: 'content',
  fields: [
    { key: 'heading', label: 'Heading', type: 'text', defaultValue: 'Welcome to My Site' },
    { key: 'subheading', label: 'Subheading', type: 'text', defaultValue: 'Build something amazing today' },
    { key: 'bgImage', label: 'Background Image', type: 'image', defaultValue: '' },
    { key: 'overlayColor', label: 'Overlay Color', type: 'color', defaultValue: '#0f1117' },
    { key: 'overlayOpacity', label: 'Overlay Opacity', type: 'number', defaultValue: 70 },
    { key: 'ctaText', label: 'Button Text', type: 'text', defaultValue: 'Get Started' },
    { key: 'ctaUrl', label: 'Button URL', type: 'url', defaultValue: '#' },
    { key: 'ctaColor', label: 'Button Color', type: 'color', defaultValue: '#6366f1' },
    { key: 'alignment', label: 'Alignment', type: 'select', defaultValue: 'center', options: [
      { label: 'Left', value: 'left' },
      { label: 'Center', value: 'center' },
      { label: 'Right', value: 'right' },
    ]},
    { key: 'textColor', label: 'Text Color', type: 'color', defaultValue: '#ffffff' },
  ],
  defaultProps: {
    heading: 'Welcome to My Site',
    subheading: 'Build something amazing today',
    bgImage: '',
    overlayColor: '#0f1117',
    overlayOpacity: 70,
    ctaText: 'Get Started',
    ctaUrl: '#',
    ctaColor: '#6366f1',
    alignment: 'center',
    textColor: '#ffffff',
  },
  resizable: { width: false, height: true },
  minHeight: 400,
};
